# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=80)),
                ('released', models.DateField()),
                ('summary', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('secret', models.CharField(max_length=32)),
                ('option1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option1', to='worlds_of_zzt.Option')),
                ('option2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option2', to='worlds_of_zzt.Option')),
                ('option3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option3', to='worlds_of_zzt.Option')),
                ('option4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option4', to='worlds_of_zzt.Option')),
                ('option5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option5', to='worlds_of_zzt.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds_of_zzt.Option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds_of_zzt.Poll')),
            ],
        ),
    ]
